### ISSUE TITLE
Input - Console Prompt

### ISSUE THREAD

**Issue by jwood36** [TatumS1/HW_TicTacToe_Task1_-tstigna1-.md#10]
Refer to #4 

Console Input still does not have a Prompt.

**Comment by TatumS1** [comment]
I have not been updating the code live within GitHub, I am still testing things but check them off as I go.

From: jwood36 ***@***.***>
Sent: Monday, March 6, 2023 5:57 PM
To: TatumS1/HW_TicTacToe_Task1_-tstigna1-.md ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TatumS1/HW_TicTacToe_Task1_-tstigna1-.md] Input - Console Prompt (Issue #10)


CAUTION: This message did not originate from Jefferson State.

Refer to #4<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fprotect-us.mimecast.com%2Fs%2FutdgCv26OBh757AhXaTj6%3Fdomain%3Dgithub.com&data=05%7C01%7Ctstigna1%40jeffersonstate.edu%7Ca9c8c3c4dea34f76029808db1e9e87b6%7C09d24dd3d25b47b29b0f6b2789e53bd7%7C0%7C0%7C638137438477726398%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BbEP75Kr38S5yd8ubxEaA3%2BWoQA7nboFkEH9LaHR0AQ%3D&reserved=0>

Console Input still does not have a Prompt.

-

**Comment by jwood36** [comment]
You should be using Git Extensions to make commits.  You should not be making changes directly in GitHub.

John M. Wood
Instructor - Business, CIS
e: ***@***.***


________________________________________

**Comment by jwood36** [comment]
Prompt: Verified
