### ISSUE TITLE
Console Output - Abstract

### ISSUE THREAD

**Issue by jwood36** [TatumS1/HW_TicTacToe_Task1_-tstigna1-.md#6]
Abstract your "Console.Write..." calls into a single method.

I have given you suggestions through the class & labs on how to leverage Generics.

**Comment by TatumS1** [comment]
Where can I find these suggestions?

**Comment by jwood36** [comment]
Through the Lab sessions and previous programming classes.  Separation of Concerns and Abstractive Design principles that should have been taught in previous class(es).

**Comment by TatumS1** [comment]
Are these lab sessions exclusively in person or can I find them remotely as I have a conflicting schedule from what I can tell in your calendar.

**Comment by jwood36** [comment]
All lab sessions are recorded for later consumption.

John M. Wood
Instructor - Business, CIS
e: ***@***.***


________________________________________
